- name: Add OpenNebula 5.4 repo
  yum_repository:
    name: opennebula
    description: OpenNebula 5.4 repo
    baseurl: http://downloads.opennebula.org/repo/5.4/CentOS/7/x86_64
    gpgcheck: no
    enabled: yes

- name: Install opennebula
  yum: name={{item}}
  with_items:
    - opennebula
    - opennebula-server

- name: Delete pregenerated password for core
  file:
    path: /var/lib/one/.one/one_auth
    state: absent

- name: Set default password for core
  become_user: oneadmin
  lineinfile:
    path: /var/lib/one/.one/one_auth
    line: oneadmin:test
    create: yes
    mode: 0700

- name: Enable and start opennebula
  service:
    name: opennebula
    state: started
    enabled: yes

- name: Delete pregenerated password for sunstone
  file:
    path: /var/lib/one/.one/sunstone_auth
    state: absent

- name: Set default password for sunstone
  become_user: oneadmin
  lineinfile:
    path: /var/lib/one/.one/sunstone_auth
    line: serveradmin:testtesttest
    create: yes
    mode: 0700

- name: Change password for sunstone_auth
  command: one_user passwd 1 testtesttest --sha1
  notify:
    - Restart opennebula

- name: Open port for opennebula
  firewalld:
    port: 2633/tcp
    permanent: true
    state: enabled
  notify:
    - Restart firewalld

